### ISSUE TITLE
bug: unable to configure mode from `forge.yaml` or `forge.default.yaml`

### ISSUE THREAD

**Issue by laststylebender14** [antinomyhq/forge#791]
Unable to configure the PLAN mode from `forge.yaml` or `forge.default.yaml` file.

```yaml
variables:
  mode: PLAN
model: anthropic/claude-3.7-sonnet
```
