### ISSUE TITLE
add support for a global api key config file

### ISSUE THREAD

**Issue by johnpyp** [antinomyhq/forge#858]
I'd like to be able to set global api keys for Forge, which isn't possible right now afaict because it *only* resolves from env.

- codex supports this: https://github.com/openai/codex?tab=readme-ov-file#full-configuration-example
- claude code supports this (default it saves your key to a global config file)
- goose saves keys into the system keyring
- etc..

**Comment by tusharmath** [comment]
Providers could be configured via `forge.yaml`. Would that work for you?

**Comment by johnpyp** [comment]
As long as I can do like `~/.config/forge/forge.yaml` then yeah :)

**Comment by jayantpranjal0** [comment]
@amitksingh1490 I would like to work on this

**Comment by jayantpranjal0** [comment]
@tusharmath just wanted to confirm how to approach the issue. Since, right now two types of providers are supported: OpenAI and anthropic, we have to also know which type of provider to be used. 
So just to confirm, we have to add the feature to  add a list of providers: 
```
provider_id: openai
providers:
  - id: openai
    name: OpenAI
    description: OpenAI API provider
    api_key: OPENAI_API_KEY
    type: openai
    base_url: https://api.openai.com/v1
  - id: anthropic
    name: Anthropic
    description: Anthropic API provider
    api_key: ANTHROPIC_API_KEY
    type: anthropic
    base_url: https://api.anthropic.com/v1
  - id: forge
    naeme: Forge
    description: Forge API provider
    api_key: FORGE_KEY
    type: openai
    base_url: https://antinomy.ai/api/v1/"
  - id: openrouter
    name: OpenRouter
    description: OpenRouter API provider
    api_key: OPENROUTER_API_KEY
    type: openai
    base_url: https://api.openrouter.ai/v1
  - id: azure
    name: Azure OpenAI
    description: Azure OpenAI API provider
    api_key: AZURE_OPENAI_API_KEY
    type: openai
    base_url: https://api.openai.azure.com/v1
```
Also, to ensure that this still compatible with previous releases, will also have to default to the values of first 4 if not mentioned explicitly in forge.yaml, which was hardcoded before.
